### ISSUE TITLE
obj importer does not work for anonymous meshes

### ISSUE THREAD

**Issue by MichalisTamiolakis** [papagiannakis/pyGLV#23]
Error:

Traceback (most recent call last):
  File "d:\Documents\Git\Elements\pyGLV\pyGLV\examples\example_6_import_objects.py", line 117, in <module>
    imported_obj = Wavefront(obj_to_import)
  File "D:\Documents\Git\Elements\pyGLV\pyGLV\GL\objimporter\wavefront.py", line 38, in __init__
    self.__parse_from_file(encoding)
  File "D:\Documents\Git\Elements\pyGLV\pyGLV\GL\objimporter\wavefront.py", line 62, in __parse_from_file
    if line[0] == "#" or len(line)<1:

is thrown when trying to import .obj file that does not have a 'o [name]' command in it

**Comment by kamarianakis** [comment]
Work is to be done on feature branch [fixing_importer](https://github.com/papagiannakis/pyGLV/tree/feature/fixing_importer)
